CREATE EXTENSION IF NOT EXISTS CITEXT;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS forums;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS votes;


CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email citext NOT NULL UNIQUE,
    nickname citext NOT NULL UNIQUE,
    fullname text DEFAULT NULL,
    about text DEFAULT NULL
);

CREATE TABLE forums (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug citext NOT NULL UNIQUE,
    title text NOT NULL,
    username citext NOT NULL,
    threads integer DEFAULT 0,
    posts integer DEFAULT 0
);

CREATE TABLE threads (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug citext NOT NULL,
    created timestamptz DEFAULT NOW(),
    title text NOT NULL,
    message text DEFAULT NULL,
    username integer NOT NULL,
    -- forum_id integer NOT NULL,
    votes integer DEFAULT 0
);

CREATE TABLE posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamptz DEFAULT NOW(),
    isedited boolean DEFAULT FALSE,
    message text DEFAULT NULL,
    user_id integer NOT NULL,
    parents integer DEFAULT NULL,
    thread_id integer NOT NULL
);

CREATE TABLE votes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id integer NOT NULL,
    user_id integer NOT NULL,
    value integer NOT NULL
);
